### ISSUE TITLE
Optionally broadcast transactions to all fallback nodes too

### ISSUE THREAD

**Issue by snoyberg** [fpco/cosmos-rs#11]
Each `Cosmos` connection includes one primary node and 0 or more fallback nodes. Generally, we only use the fallback nodes when there's an issue with the primary nodes. However, recently, we've observed an issue with Osmosis where occasionally:

* Our primary node is working as far as we can tell: queries work, blocks don't lag, etc.
* Broadcasting transactions to our primary node works, meaning that the broadcast itself succeeds
* However, the node has issues with its peers and is unable to continue propagating our transaction to validator nodes

One mitigation I thought of: each time we broadcast a transaction, automatically broadcast to all of our fallback nodes too, or at least the ones still marked as healthy. We can ignore any errors that happen during this broadcast. But in theory, this would allow us to route around a primary node that's having peer issues.

**Comment by qrilka** [comment]
@snoyberg what would be a proper way to test this kind of change? It seems that the repo contains not so many tests and I didn't find any multi-node scenarios. Could you share your suggestions maybe?

**Comment by snoyberg** [comment]
I didn't have a particular testing strategy in mind.

**Comment by qrilka** [comment]
@psibi maybe you could have an advice how to test multi-node functionality like this?

**Comment by psibi** [comment]
Sorry, I'm not sure what would be a good way to test it. Probably you can log the response after broadcasting to do do some sanity testing ?

**Comment by qrilka** [comment]
Thanks @psibi , and I guess I need localosmosis to spawn a test network or maybe there are some better tools?

**Comment by psibi** [comment]
> I guess I need localosmosis to spawn a test network 

Yeah, I prefer using localosmosis to test locally.

**Comment by snoyberg** [comment]
This bumped in priority, I'm going to implement it myself.

**Comment by snoyberg** [comment]
Implemented in #19
